### ISSUE TITLE
Complex MOI

### ISSUE THREAD

**Issue by blegat** [chriscoey/Hypatia.jl#540]
I'd like to investigate how Complex support can be done in MOI.
I suggest starting a repo ComplexOptInterface.jl (COI) where we can add new MOI set, bridges and experiment. We can add sets or bridges that may not be merged into MOI, it's just experiments.
Do you have any bridges to share in COI ?

**Comment by matbesancon** [comment]
@blegat is this issue still relevant now that COI is in good shape?

**Comment by blegat** [comment]
My question is still open. are there complex bridges here ?

**Comment by chriscoey** [comment]
Hypatia doesn't implement bridges, nothing here would have been particularly helpful for COI. sorry I missed this question earlier

**Comment by blegat** [comment]
No problem, you reacted on the MOI issues anyway so I had your input
