### ISSUE TITLE
permute_affine not working with immutable array

### ISSUE THREAD

**Issue by matbesancon** [chriscoey/Hypatia.jl#793]
```julia
if needs_permute(set)
        perm_idxs = permute_affine(set, 1:dim)
        perm_idxs .+= start
        append!(IM, perm_idxs)
else
        append!(IM, idxs)
end
```
this will result in problems because permute_affine is mutating the passed array:
```
function permute_affine(cone::SpecNucCone, vals::AbstractVector{T}) where {T}
    @views vals[2:end] = reshape(vals[2:end], cone.row_dim, cone.column_dim)'
    return vals
end

```

**Comment by chriscoey** [comment]
Thanks, good point!
should be fixed by https://github.com/chriscoey/Hypatia.jl/pull/792/commits/96f57a416d67ae8da5ab3f197ded605103c95206#diff-8754e2bf9a8a760578a78a534e03e6e0144e08dc68f77bce0a904dc00e4ce970R87
