### ISSUE TITLE
Faster arbitrary precision support for SDPs

### ISSUE THREAD

**Issue by DanielBrosch** [chriscoey/Hypatia.jl#818]
While Hypatia supports arbitrary precision solving trough BigFloats, their linear algebra performance is far from fantastic. Especially matrix multiplication with BigFloats simply computes the product the naive way. Solving even small SDPs with BigFloats in Hypatia takes much longer than when using SDPA-GMP, for example.

There are multiple implementations of higher precision floats in julia: 

- BigFloat: Naive linear algebra, too slow to be practical, but supported by Hypatia.
- ArbField(precision) in [Nemo.jl](https://github.com/Nemocas/Nemo.jl): Fast linear algebra, but weird type structure. Does currently not work with Hypatia.
- [ArbNumerics.jl](https://github.com/JeffreySarnoff/ArbNumerics.jl): Custom linear algebra, but requires special matrix type `ArbFloatMatrix`. Works in Hypatia, but custom linear algebra does not get called.
- [QuadMath.jl](https://github.com/JuliaMath/Quadmath.jl): No custom linear algebra implementation.
- [DoubleFloats.jl](https://github.com/JuliaMath/DoubleFloats.jl): Fast linear algebra, but only double the precision. Works directly in Hypatia, faster than BigFloats for same precision.

[Nemo.jl](https://github.com/Nemocas/Nemo.jl) may provide the best alternative to BigFloats, [ArbField(precision)](https://nemocas.github.io/Nemo.jl/stable/arb/), as it seems to [perform much better for certain linear algebra operations](https://fredrikj.net/blog/2018/07/high-precision-linear-algebra-in-julia-bigfloat-vs-arb/).

The question is: Can Hypatia potentially support ArbFields from Nemo, or ArbFloats from ArbNumerics? They may not support all necessary operations. The main problems seem to be:

- Nemo's `arb`/`ArbField` do not inherit from the type `Real`.
- May need `arb_mat`-matrices for linear algebra. Same problem for ArbNumerics.jl.

**Comment by DanielBrosch** [comment]
I now entered the same SDP not trough Convex.jl, but the direct interface, and it's being solved much faster now. What is the best way to avoid unnecessary reformulations of an SDP in Convex.jl, if given in linear matrix inequality form? No matter whether I enter it in primal or dual form, Convex always seems to add many unnecessary variables and constraints...

**Comment by lkapelevich** [comment]
Hey @DanielBrosch. I don't know why Convex.jl would add variables for an SDP. Are there complex numbers involved? When you say "direct interface", are you just using Hypatia's `PosSemidefTri`, cone or did you use the `LinMatrixIneq` cone?

**Comment by DanielBrosch** [comment]
Hey @lkapelevich, sorry for the late reply. There are no complex numbers involved, just an SDP in standard primal form as you give here https://chriscoey.github.io/Hypatia.jl/stable/modeling/. When I enter trough it in Convex.jl, additional equalities are added (for every matrix entry I suppose), despite it not being necessary.  

When I build the model directly using Hypatia's Hypatia.Models.Model{K}(c,A,b,G,h}, with Hypatia.Cones.PosSemidefTri cones, the problem is solved much faster.

I will try to code up a minimal example showing you how I enter the problem, as I assume that I'm making some mistakes with Convex.jl's interface.

**Comment by odow** [comment]
This seems like an issue for Convex.jl. It doesn't appear to be a bug in Hypatia?

**Comment by lkapelevich** [comment]
It can be reopened if there is still an issue.
