### ISSUE TITLE
Add support for MOI.HermitianPositiveSemidefiniteConeTriangle

### ISSUE THREAD

**Issue by araujoms** [chriscoey/Hypatia.jl#821]
If I create a model in JuMP with `model = Model(Hypatia.Optimizer; add_bridges=false)`, add a Hermitian PSD variable `@variable(model, [1:2, 1:2] in HermitianPSDCone())`, and try to optimize it I get the error 

"MathOptInterface.UnsupportedConstraint{MathOptInterface.VectorOfVariables, MathOptInterface.HermitianPositiveSemidefiniteConeTriangle}: `MathOptInterface.VectorOfVariables`-in-`MathOptInterface.HermitianPositiveSemidefiniteConeTriangle` constraint is not supported by the model"

But Hypatia supposedly does support it, see [the documentation](https://chriscoey.github.io/Hypatia.jl/dev/api/cones/#Hypatia.Cones.PosSemidefTri).

If I add instead `@variable(model, [1:2, 1:2] in PSDCone())` it works as expected.

I opened this issue before in JuMP jump-dev/JuMP.jl#3306, but the dev @odow told me that it needs to be supported here, not there.

**Comment by chriscoey** [comment]
Hey @araujoms, yes - MOI only started supporting this set recently, so we will have to enable it through Hypatia's MOI interface. I'll have a look at that now.

**Comment by araujoms** [comment]
Ok, I've tested it here, works like a charm.

I'm just unhappy that Hypatia doesn't say the number of variables and constraints it is using, so I can't know whether it is using complex numbers optimally short of benchmarking.
