### ISSUE TITLE
Dual of log-det cone

### ISSUE THREAD

**Issue by blegat** [chriscoey/Hypatia.jl#827]
I can see here:
https://github.com/chriscoey/Hypatia.jl/blob/7f81cf26cd051bcd22203c4dd8c901b4460da03b/src/Cones/hypoperlogdettri.jl#L120-L133
that you have implemented a check for membership for the dual of the log-det cone.
Do you have the definition of this cone somewhere in the Hypatia paper or thesis ?

**Comment by lkapelevich** [comment]
Equation 19b https://arxiv.org/pdf/2005.01136.pdf

**Comment by blegat** [comment]
Thanks!
